"use client"

import { useEffect, useState, useRef } from "react"
import { useSession } from "next-auth/react"

export default function Studio() {
    const { data: session } = useSession(); 
    
    // --- STATE MANAGEMENT ---
    const [file, setFile] = useState<File | null>(null);
    const [audioURL, setAudioURL] = useState<string | null>(null);
    const [isUploading, setIsUploading] = useState(false);
    const [midiUrl, setMidiUrl] = useState<string | null>(null);
    
    // NEW: We need to track if the user is currently hovering a file over our dropzone
    const [dragActive, setDragActive] = useState(false);
    // NEW: A reference to physically click the hidden HTML input when they click the stylized box
    const inputRef = useRef<HTMLInputElement>(null);

    // Memory Management for Audio URLs
    useEffect(() => {
        if (file) {
            const url = URL.createObjectURL(file)
            setAudioURL(url)
            return () => URL.revokeObjectURL(url)
        }
    }, [file]);

    useEffect(() => {
        return () => { if (midiUrl) URL.revokeObjectURL(midiUrl); }
    }, [midiUrl]);

    // --- EVENT HANDLERS ---
    
    // Triggered when a file is selected via standard click
    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            setFile(e.target.files[0]);
            setMidiUrl(null); 
        }
    };

    // The Drag & Drop State Machine
    const handleDrag = (e: React.DragEvent) => {
        e.preventDefault(); // Stops the browser from opening the audio file in a new tab
        e.stopPropagation();
        if (e.type === "dragenter" || e.type === "dragover") {
            setDragActive(true); // User is hovering a file
        } else if (e.type === "dragleave") {
            setDragActive(false); // User moved the file away
        }
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setDragActive(false); // Turn off the hover effect
        if (e.dataTransfer.files && e.dataTransfer.files[0]) {
            setFile(e.dataTransfer.files[0]); // Grab the dropped file
            setMidiUrl(null);
        }
    };

    // --- API COMMUNICATION ---
    const handleUpload = async () => {
        if (!file) return;
        setIsUploading(true);
        setMidiUrl(null); 

        const formData = new FormData();
        formData.append("file", file);

        try {
            // 1. Send to The Vault (Phase 8 Backend)
            const response = await fetch("/api/upload", {
                method: "POST",
                body: formData
            });

            const contentType = response.headers.get("content-type") || "";
            const isJson = contentType.includes("application/json");
            const data = isJson ? await response.json() : null;
            const textBody = isJson ? "" : await response.text();

            if (!response.ok) {
                throw new Error(
                    data?.details ||
                    data?.error ||
                    textBody ||
                    "Upload Failed"
                );
            }
            
            // 2. Deduplication Check
            if (data?.deduplicated) {
                console.log("Compute Saved! This file was already in the Vault.");
            } else {
                console.log("New file processed and uploaded successfully.");
            }

            // 3. Use the real MIDI generated by the backend
            setMidiUrl(data?.midiUrl || null);
            
        } catch (error: any) {
            console.error("Upload Failed : ", error);
            alert(error.message || "Failed to analyze beat.");
        } finally {
            setIsUploading(false);
        }
    };

    return (
        <main className="app-container">
            <div className="w-full max-w-3xl mx-auto flex flex-col items-center gap-10">
                
                {/* Header Section */}
                <div className="text-center space-y-4">
                    <h1 className="ui-title text-4xl md:text-5xl">
                        The <span className="ui-gradient">Studio</span>
                    </h1>
                    <p className="ui-muted text-base md:text-lg">
                        {session?.user?.name ? `${session.user.name}, initialize` : "Initialize"} the neural network with a raw drum loop.
                    </p>
                </div>

                {/* The Glassmorphism Console */}
                <div className="glass-panel w-full p-8 md:p-12 rounded-4xl shadow-2xl flex flex-col items-center gap-8 relative overflow-hidden">
                    
                    {/* Subtle inner glow */}
                    <div className="absolute inset-0 bg-linear-to-b from-white/2 to-transparent pointer-events-none"></div>

                    {/* The Drag & Drop Zone */}
                    <div 
                        onDragEnter={handleDrag}
                        onDragLeave={handleDrag}
                        onDragOver={handleDrag}
                        onDrop={handleDrop}
                        onClick={() => inputRef.current?.click()}
                        className={`relative w-full h-48 rounded-3xl border-2 border-dashed flex flex-col items-center justify-center transition-all duration-300 cursor-pointer group ${
                            dragActive 
                                ? "border-purple-500 bg-purple-500/10 scale-[1.02]" // Active hover state
                                : "border-neutral-700 hover:border-neutral-500 bg-black/50" // Idle state
                        }`}
                    >
                        {/* Hidden input - triggered by the onClick of the parent div */}
                        <input
                            ref={inputRef}
                            type="file"
                            accept="audio/*"
                            onChange={handleFileChange}
                            className="hidden"
                        />
                        
                        {/* Dynamic UI inside the Dropzone */}
                        <div className="flex flex-col items-center gap-3 pointer-events-none">
                            {file ? (
                                <>
                                    {/* Success Icon */}
                                    <div className="w-12 h-12 rounded-full bg-green-500/20 flex items-center justify-center text-green-400 mb-2">
                                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
                                    </div>
                                    <p className="text-white font-medium text-lg">{file.name}</p>
                                    <p className="text-neutral-500 text-sm">{(file.size / 1024 / 1024).toFixed(2)} MB • Click to replace</p>
                                </>
                            ) : (
                                <>
                                    {/* Upload Icon */}
                                    <div className={`w-14 h-14 rounded-full flex items-center justify-center mb-2 transition-colors ${dragActive ? "bg-purple-500 text-white" : "bg-white/5 text-neutral-400 group-hover:bg-white/10 group-hover:text-white"}`}>
                                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path></svg>
                                    </div>
                                    <p className="text-neutral-300 font-medium text-lg">Drag & Drop audio here</p>
                                    <p className="text-neutral-600 text-sm">Supports WAV, MP3, AIFF</p>
                                </>
                            )}
                        </div>
                    </div>

                    {/* Stylized Audio Player Wrapper */}
                    {audioURL && (
                        <div className="w-full bg-black/60 p-4 rounded-2xl border border-white/5 shadow-inner">
                            <div className="flex items-center gap-4 mb-2 px-2">
                                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
                                <span className="text-xs text-neutral-400 font-mono tracking-wider">AUDIO_INPUT_STREAM</span>
                            </div>
                            <audio controls src={audioURL} className="w-full h-12 outline-none opacity-80 hover:opacity-100 transition-opacity [&::-webkit-media-controls-panel]:bg-neutral-900 [&::-webkit-media-controls-current-time-display]:text-white [&::-webkit-media-controls-time-remaining-display]:text-white" />
                        </div>
                    )}

                    {/* Action Buttons */}
                    <div className="w-full mt-4">
                        {!midiUrl ? (
                            <button
                                onClick={handleUpload}
                                disabled={!file || isUploading}
                                className="w-full relative px-8 py-5 bg-white text-black font-bold text-lg rounded-2xl disabled:opacity-30 disabled:cursor-not-allowed hover:bg-neutral-200 hover:scale-[1.02] transition-all active:scale-95 shadow-[0_0_40px_rgba(255,255,255,0.1)]"
                            >
                                {isUploading ? (
                                    <span className="flex items-center justify-center gap-3">
                                        <svg className="animate-spin h-5 w-5 text-black" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                                        Extracting Bassline Matrix...
                                    </span>
                                ) : (
                                    "Initialize Engine"
                                )}
                            </button>
                        ) : (
                            <div className="w-full space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
                                <div className="flex items-center justify-center gap-2 text-green-400 text-sm font-medium tracking-wide">
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                    MIDI Synthesized Successfully
                                </div>
                                <a
                                    href={midiUrl}
                                    download="RhythmAI_Bassline.mid"
                                    className="flex items-center justify-center gap-3 w-full px-8 py-5 bg-linear-to-r from-purple-600 to-indigo-600 text-white font-bold text-lg rounded-2xl hover:shadow-[0_0_30px_rgba(147,51,234,0.4)] hover:scale-[1.02] active:scale-95 transition-all"
                                >
                                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                                    Download MIDI File
                                </a>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </main>
    );
}