"use client"

import { useEffect, useState, useRef } from "react"
import { useSession } from "next-auth/react"

export default function Studio() {
    const { data: session } = useSession(); 
    
    // --- STATE MANAGEMENT ---
    const [file, setFile] = useState<File | null>(null);
    const [audioURL, setAudioURL] = useState<string | null>(null);
    const [isUploading, setIsUploading] = useState(false);
    const [midiUrl, setMidiUrl] = useState<string | null>(null);
    
    // NEW: We need to track if the user is currently hovering a file over our dropzone
    const [dragActive, setDragActive] = useState(false);
    // NEW: A reference to physically click the hidden HTML input when they click the stylized box
    const inputRef = useRef<HTMLInputElement>(null);

    // Memory Management for Audio URLs
    useEffect(() => {
        if (file) {
            const url = URL.createObjectURL(file)
            setAudioURL(url)
            return () => URL.revokeObjectURL(url)
        }
    }, [file]);

    useEffect(() => {
        return () => { if (midiUrl) URL.revokeObjectURL(midiUrl); }
    }, [midiUrl]);

    // --- EVENT HANDLERS ---
    
    // Triggered when a file is selected via standard click
    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            setFile(e.target.files[0]);
            setMidiUrl(null); 
        }
    };

    // The Drag & Drop State Machine
    const handleDrag = (e: React.DragEvent) => {
        e.preventDefault(); // Stops the browser from opening the audio file in a new tab
        e.stopPropagation();
        if (e.type === "dragenter" || e.type === "dragover") {
            setDragActive(true); // User is hovering a file
        } else if (e.type === "dragleave") {
            setDragActive(false); // User moved the file away
        }
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setDragActive(false); // Turn off the hover effect
        if (e.dataTransfer.files && e.dataTransfer.files[0]) {
            setFile(e.dataTransfer.files[0]); // Grab the dropped file
            setMidiUrl(null);
        }
    };

    // --- API COMMUNICATION ---
    const handleUpload = async () => {
        if (!file) return;
        setIsUploading(true);
        setMidiUrl(null); 

        const formData = new FormData();
        formData.append("file", file);

        try {
            // 1. Send to The Vault (Phase 8 Backend)
            const response = await fetch("/api/upload", {
                method: "POST",
                body: formData
            });

            const contentType = response.headers.get("content-type") || "";
            const isJson = contentType.includes("application/json");
            const data = isJson ? await response.json() : null;
            const textBody = isJson ? "" : await response.text();

            if (!response.ok) {
                throw new Error(
                    data?.details ||
                    data?.error ||
                    textBody ||
                    "Upload Failed"
                );
            }
            
            // 2. Deduplication Check
            if (data?.deduplicated) {
                console.log("Compute Saved! This file was already in the Vault.");
            } else {
                console.log("New file processed and uploaded successfully.");
            }

            // 3. Use the real MIDI generated by the backend
            setMidiUrl(data?.midiUrl || null);
            
        } catch (error: any) {
            console.error("Upload Failed : ", error);
            alert(error.message || "Failed to analyze beat.");
        } finally {
            setIsUploading(false);
        }
    };

    return (
        <main className="app-container">
            <div className="mx-auto flex w-full max-w-3xl flex-col items-center gap-8 md:gap-10">
                
                {/* Header Section */}
                <div className="text-center space-y-4">
                    <h1 className="ui-title text-3xl sm:text-4xl md:text-5xl">
                        The <span className="ui-gradient">Studio</span>
                    </h1>
                    <p className="ui-muted text-sm sm:text-base md:text-lg">
                        {session?.user?.name ? `${session.user.name}, initialize` : "Initialize"} the neural network with a raw drum loop.
                    </p>
                </div>

                {/* The Glassmorphism Console */}
                <div className="glass-panel ui-card-hover relative flex w-full flex-col items-center gap-6 overflow-hidden rounded-3xl p-5 shadow-2xl sm:p-7 md:gap-8 md:p-12">
                    
                    {/* Subtle inner glow */}
                    <div className="pointer-events-none absolute inset-0 bg-linear-to-b from-white/5 to-transparent"></div>

                    {/* The Drag & Drop Zone */}
                    <div 
                        onDragEnter={handleDrag}
                        onDragLeave={handleDrag}
                        onDragOver={handleDrag}
                        onDrop={handleDrop}
                        onClick={() => inputRef.current?.click()}
                        className={`group relative flex h-44 w-full cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed transition-all duration-300 md:h-48 ${
                            dragActive 
                                ? "scale-[1.02] border-cyan-400 bg-cyan-400/10"
                                : "border-slate-600/80 bg-black/45 hover:border-slate-400"
                        }`}
                    >
                        {/* Hidden input - triggered by the onClick of the parent div */}
                        <input
                            ref={inputRef}
                            type="file"
                            accept="audio/*"
                            onChange={handleFileChange}
                            className="hidden"
                        />
                        
                        {/* Dynamic UI inside the Dropzone */}
                        <div className="flex flex-col items-center gap-3 pointer-events-none">
                            {file ? (
                                <>
                                    {/* Success Icon */}
                                    <div className="w-12 h-12 rounded-full bg-green-500/20 flex items-center justify-center text-green-400 mb-2">
                                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
                                    </div>
                                    <p className="max-w-[90%] truncate text-lg font-medium text-white">{file.name}</p>
                                    <p className="text-sm text-slate-400">{(file.size / 1024 / 1024).toFixed(2)} MB • Click to replace</p>
                                </>
                            ) : (
                                <>
                                    {/* Upload Icon */}
                                    <div className={`mb-2 flex h-14 w-14 items-center justify-center rounded-full transition-colors ${dragActive ? "bg-cyan-500 text-white" : "bg-white/5 text-slate-400 group-hover:bg-white/10 group-hover:text-white"}`}>
                                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path></svg>
                                    </div>
                                    <p className="text-lg font-medium text-slate-200">Drag and drop audio here</p>
                                    <p className="text-sm text-slate-500">Supports WAV, MP3, AIFF</p>
                                </>
                            )}
                        </div>
                    </div>

                    {/* Stylized Audio Player Wrapper */}
                    {audioURL && (
                        <div className="w-full rounded-2xl border border-white/10 bg-black/60 p-4 shadow-inner">
                            <div className="mb-2 flex items-center gap-4 px-2">
                                <div className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"></div>
                                <span className="font-mono text-xs tracking-wider text-slate-400">AUDIO_INPUT_STREAM</span>
                            </div>
                            <audio controls src={audioURL} className="w-full h-12 outline-none opacity-80 hover:opacity-100 transition-opacity [&::-webkit-media-controls-panel]:bg-neutral-900 [&::-webkit-media-controls-current-time-display]:text-white [&::-webkit-media-controls-time-remaining-display]:text-white" />
                        </div>
                    )}

                    {/* Action Buttons */}
                    <div className="w-full mt-4">
                        {!midiUrl ? (
                            <button
                                onClick={handleUpload}
                                disabled={!file || isUploading}
                                className="ui-focus relative w-full rounded-2xl bg-white px-8 py-4 text-base font-bold text-black shadow-[0_0_40px_rgba(255,255,255,0.1)] transition-all hover:scale-[1.02] hover:bg-neutral-200 active:scale-95 disabled:cursor-not-allowed disabled:opacity-30 md:py-5 md:text-lg"
                            >
                                {isUploading ? (
                                    <span className="flex items-center justify-center gap-3">
                                        <svg className="animate-spin h-5 w-5 text-black" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                                        Extracting Bassline Matrix...
                                    </span>
                                ) : (
                                    "Initialize Engine"
                                )}
                            </button>
                        ) : (
                            <div className="fade-up w-full space-y-4">
                                <div className="flex items-center justify-center gap-2 text-sm font-medium tracking-wide text-emerald-400">
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                    MIDI Synthesized Successfully
                                </div>
                                <a
                                    href={midiUrl}
                                    download="RhythmAI_Bassline.mid"
                                    className="ui-focus flex w-full items-center justify-center gap-3 rounded-2xl bg-linear-to-r from-sky-500 to-cyan-500 px-8 py-4 text-base font-bold text-white transition-all hover:scale-[1.02] hover:shadow-[0_0_30px_rgba(14,165,233,0.4)] active:scale-95 md:py-5 md:text-lg"
                                >
                                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                                    Download MIDI File
                                </a>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </main>
    );
}